### ISSUE TITLE
Include comments

### ISSUE THREAD

**Issue by Antriel** [sebbernery/haxe-phaser3#1]
Hi,

this is great work, but it would be even more useful if the generated externs also included the original comments.

**Comment by sebbernery** [comment]
Hi !
Good point, with comments, it'll be possible to generate Haxe documentation, can be cool. I'll check this week if I can implement that.
Thanks for your feedback.

**Comment by sebbernery** [comment]
Done, I'll try to generate the Haxe documentation later.
