### ISSUE TITLE
3.16.2 build generated invalid file names

### ISSUE THREAD

**Issue by Antriel** [sebbernery/haxe-phaser3#4]
E.g. `EachListCallback<I>.hx` instead of `EachListCallback.hx`. Which behaves weirdly in zip files so haxelib install fails.

**Comment by sebbernery** [comment]
I updated it, it should be better.

**Comment by Antriel** [comment]
That was fast :+1:, but seems like it also removed some files that were OK.

**Comment by sebbernery** [comment]
It's because sometimes, I forget to delete all files before regenerating bindings. I did it this time. Deleted files were valid for previous Phaser version but they no more exists.
